export component Test {
    in property <float> progress: 0.5;
    Path {
        stroke: red;
        stroke-width: 5px;
        MoveTo { x: 50; y: 0; }
        ArcTo {
            radius-x: 50; radius-y: 50;
            x: 50 + 50 * sin(root.progress * 360deg);
            y: 50 - 50 * cos(root.progress * 360deg);
            sweep: true;
            large-arc: root.progress > 0.5;
        }
    }
    Text { text: round(root.progress * 100) + "%"; }
}
